### PR TITLE
Add chtnnh.cpp to Magnets

### PR DESCRIPTION
**Pull request by chtnnh**
Kindly add the hacktoberfest-accepted label when merging :D

### CODE REVIEW

**Review by sidanand67 — CHANGES_REQUESTED** [review]
You are requested to either add comments or use appropriate variable names.

**Comment by sidanand67** [comment]
Label is only required when the PR is acceptable and would be merged later.
No label is required if the PR is merged in the hactoberfest tagged repo.

**Comment by chtnnh** [comment]
Kindly have a look now

**Comment by sidanand67** [comment]
Thanks for contributing.

**Pull request merged**
