### PR TITLE
A->soldier-and-banana->fazeel.py

### PR DESCRIPTION
**Pull request by FazeelUsmani**
Accepted on Codeforces

### CODE REVIEW

**Review by sidanand67 — CHANGES_REQUESTED** [review]
You are requested to either add comments or use appropriate variable names.
Also, rename your code file as "your_username.py".

**Comment by FazeelUsmani** [comment]
Sure, @sidanand67. Will add comments

**Review by FazeelUsmani — COMMENTED** [review]
added comments for variables

**Review by FazeelUsmani — COMMENTED** [review]
added documentation

**Comment by sidanand67** [comment]
Thanks for contributing.

**Pull request merged**
