### PR TITLE
petya and strings added

### PR DESCRIPTION
**Pull request by shivangigoel1302**

### CODE REVIEW

**Review by sidanand67 — CHANGES_REQUESTED** [review]
Thanks for contributing but you are required to either add comments in your code or use appropriate variable and function names.
Also, name the codefile with your_username.cpp.
Post these changes, I'll merge your commit.

**Comment by shivangigoel1302** [comment]
I have made the mentioned changes . Do check .thankyou

**Comment by sidanand67** [comment]
Thanks for contributing.

**Comment by sidanand67** [comment]
I've to delete your code as it's giving WA on codeforces.
You are requested to resubmit a working code. 
Thankyou.

**Pull request merged**
