### PR TITLE
Add chtnnh.c to Vanya_and_Fence

### PR DESCRIPTION
**Pull request by chtnnh**
Kindly add the hacktoberfest-approved label when merging :D

### CODE REVIEW

**Comment by chtnnh** [comment]
I hope you dont mind the multiple pull requests, I just found your repo and really support the initiative. I am adding all the solutions I have been able to reach!

**Review by sidanand67 — CHANGES_REQUESTED** [review]
You are requested to either add comments or use appropriate variable names.

**Comment by chtnnh** [comment]
@sidanand67 Kindly have a look now

**Comment by sidanand67** [comment]
Thanks for contributing.

**Pull request merged**
