### PR TITLE
Add: Problem 231A, A. Team, codeforces solution in c++

### PR DESCRIPTION
**Pull request by rsrahul1000**
## Problem Name
- Team

## Problem Link
[A Team Problem Statement](https://codeforces.com/problemset/problem/231/A)

## Issue Reference assigned to me
#57 

## Coding Rules to Follow
- [x] Proper Indentation is must.
- [x] Include comments wherever required so as to make the code easily understandable.
- [x] Place your code in right directory.
- [x] Name your code file with your username. 
- [x] Proper naming of variables and functions is must throughout the code.

### CODE REVIEW

**Comment by sidanand67** [comment]
Thanks for contributing.

**Comment by rsrahul1000** [comment]
Thanks for review and merge, this is a good repo for CP ;)

**Comment by sidanand67** [comment]
Thankyou. 
I really liked the way you committed.
I wanna know how did you add those "Coding Rules" in your commit?

**Comment by rsrahul1000** [comment]
Thanks
Well you can add those Coding Rules To Follow in the Contributing Instructions an make a Demo Template for them to use whenever they are going to make a Pull Request so that you can manage and make sure you are merging only the ones who are assigning the task and can mark invalid to the ones who just make pull request without a task being assigned to them.

I had just refered you CONTRIBUTING.md and then added few markdown syntax to make it a check box by using "- [ x ] "

**Comment by sidanand67** [comment]
Thanks for the input. This was really helpful suggestion.

**Pull request merged**
