### PR TITLE
Added B Presidential's_Office

### PR DESCRIPTION
**Pull request by MananOO12**
Happy Hacktober fest

President's Office - CF6-D2-B

### CODE REVIEW

**Review by sidanand67 — CHANGES_REQUESTED** [review]
You are requested to do the following:
1. Name your folder name as "President's_Office".
2. Either add comments or use appropriate variable names.

**Comment by MananOO12** [comment]
> You are requested to do the following:
> 
> 1. Name your folder name as "President's_Office".
> 2. Either add comments or use appropriate variable names.

I've updated the program please check.

**Comment by sidanand67** [comment]
You forgot to rename your folder.

**Comment by MananOO12** [comment]
> You forgot to rename your folder.

Done

**Comment by sidanand67** [comment]
Thanks for contributing.

**Pull request merged**
