### PR TITLE
added Wrong Subtraction code in c++

### PR DESCRIPTION
**Pull request by immortal-j**
#109 
I have provided the solution for the problem in c++.

### CODE REVIEW

**Review by sidanand67 — CHANGES_REQUESTED** [review]
You are requested to do the following:
1. Separate the words in problem name with an underscore(_). For ex, rename your folder to "Wrong_Subtraction".
2. Either add comments or use appropriate variable and function names.

**Comment by immortal-j** [comment]
#117 
I have added documentation and corrected the File name .

**Comment by immortal-j** [comment]
> You are requested to do the following:
> 
> 1. Separate the words in problem name with an underscore(_). For ex, rename your folder to "Wrong_Subtraction".
> 2. Either add comments or use appropriate variable and function names.

I have done all the requested changes

**Review by immortal-j — COMMENTED** [review]
Have done all the suggested changes

**Pull request merged**
