### PR TITLE
Create Soldier_and_Bananas

### PR DESCRIPTION
**Pull request by Kunal2007**

### CODE REVIEW

**Review by sidanand67 — CHANGES_REQUESTED** [review]
You were supposed to create a folder with problem name first and then add your code file into it with your username.cpp as its name.

**Comment by sidanand67** [comment]
Having any issues, just ask me.

**Comment by Kunal2007** [comment]
Sir, I am unable to create a new folder. Can you please assist me how to create that.

**Comment by sidanand67** [comment]
1. Just go into the A directory. 
2. Create a new folder with the problem name.
3. Add your code file there with your username.cpp as its name.
4. Push the changes with a new PR.

**Pull request closed without merging**
