### PR TITLE
Algorithms -> TRIE Implementation -> ninja.cpp

### PR DESCRIPTION
**Pull request by coding-ninnjas**
TRIE using cpp

### CODE REVIEW

**Comment by coding-ninnjas** [comment]
Hi, @sidanand67, have a look

**Comment by sidanand67** [comment]
Thanks for contributing.

**Comment by coding-ninnjas** [comment]
Hey! @sidanand67, Can you add **"hacktoberfest"** label to this repository?

**Comment by sidanand67** [comment]
Done

**Pull request merged**
