### PR TITLE
meteora2002.cpp

### PR DESCRIPTION
**Pull request by meteora2002**
this for bst deletion algorithm

### CODE REVIEW

**Comment by meteora2002** [comment]
@sidanand67  please check my pull request

**Review by sidanand67 — CHANGES_REQUESTED** [review]
You are requested to do the following;
1. Create a folder by the name "BST_Deletion" in Algorithms folder.
2. Rename your code file with "your_username.cpp".
3. Now, add your code file in the folder you created.

**Comment by meteora2002** [comment]
done

**Comment by meteora2002** [comment]
@sidanand67 please check my pull request

**Comment by sidanand67** [comment]
Thanks for contributing.

**Pull request merged**
