### PR TITLE
added sol for Police Recruits in c++

### PR DESCRIPTION
**Pull request by ashishburdak**

### CODE REVIEW

**Review by sidanand67 — CHANGES_REQUESTED** [review]
You are requested to add comments to explain your second "for loop".

**Comment by ashishburdak** [comment]
@sidanand67 I am contributing to open source first time, so let me know if i have done something wrong (not in code, in general) and also I have read that i can add sol available in sheet directly like this one. Can I try other sol's also and push them in the same way i did this one...... Thanks in advance :)

**Comment by sidanand67** [comment]
You have done everything correct. Yes, you can add solutions to other problems listed in the sheet in the same manner. 
The goal of this repo is to merge competitive programming experience with open source. 
Have any queries, feel free to ask.

**Comment by ashishburdak** [comment]
Ok, thank you.

**Pull request merged**
