### PR TITLE
trip-mahak.cpp

### PR DESCRIPTION
**Pull request by trip-mahak**
sum of digits solution in cpp

### CODE REVIEW

**Review by sidanand67 — CHANGES_REQUESTED** [review]
You are requested to do the following:
1. Rename your code file with your "username.cpp".
2. Add comments explaining your while(sum >= 10) loop and if(strlen(a)==1) condition.

**Comment by trip-mahak** [comment]
Done

**Comment by sidanand67** [comment]
Your file name is still the same. Kindly look into it.

**Comment by sidanand67** [comment]
thanks for contributing.

**Pull request merged**
