### PR TITLE
SerejaAndDima Solution 

### PR DESCRIPTION
**Pull request by Rohanfizz**
Solution of SerejaAndDima in C,C++ & JAVA
Peace :)

### CODE REVIEW

**Comment by Rohanfizz** [comment]
Please accept my pull Request
peace :)

**Review by sidanand67 — CHANGES_REQUESTED** [review]
You are requested to do the following:
1. Add comments or use appropriate variable or function names in "Team" file.
2. Name all  your code files with your "username.extension".

**Comment by Rohanfizz** [comment]
@sidanand67 Please take a look at the changes.
Peace :)

**Comment by sidanand67** [comment]
thanks for contributing.

**Pull request merged**
