### PR TITLE
added traveling salesman problem solution

### PR DESCRIPTION
**Pull request by pasanpasan**

### CODE REVIEW

**Review by sidanand67 — CHANGES_REQUESTED** [review]
You are requested to do the following: 
1. Move your folder to Algorithms folder.
2. Rename your code file with "your_username.cpp".

**Comment by pasanpasan** [comment]
Okay will do it now and  give a pull request

**Comment by pasanpasan** [comment]
Please can you recheck this, I have done the changes to file structure...

**Comment by sidanand67** [comment]
Thanks for contributing.

**Pull request merged**
