### PR TITLE
Added 1 .cpp file 

### PR DESCRIPTION
**Pull request by aryaniiit002**
Sum of digits #56 solved

### CODE REVIEW

**Review by sidanand67 — CHANGES_REQUESTED** [review]
You are requested to add comments explaining your while loop.

**Comment by sidanand67** [comment]
Also, name your code file in this manner. 
"your_username.cpp"

**Comment by aryaniiit002** [comment]
sum of digits.cpp is already uploaded by someone.

**Comment by sidanand67** [comment]
Don't worry. I'll merge your PR soon.

**Comment by aryaniiit002** [comment]
I have made all the changes you asked for.

**Pull request merged**
