### PR TITLE
Create Kunal2007.cpp

### PR DESCRIPTION
**Pull request by Kunal2007**
Wrote a CPP code for the problem Queue at the School. Please consider my request.

### CODE REVIEW

**Review by sidanand67 — CHANGES_REQUESTED** [review]
Is this problem in the sheet?
If yes, kindly provide me its code name.
If no, then I can't merge it as this repo is solely for sheet solutions.

**Comment by Kunal2007** [comment]
Sir, can I know which sheet are you referring to?

**Comment by Kunal2007** [comment]
Sir, can I know which sheet are you referring to?

**Comment by sidanand67** [comment]
Link to the sheet is mentioned in the readme.md and contributing.md files.
Kindly look into it.

**Pull request closed without merging**
